project_id = "apxsxhaftjqqidysiktn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[studio]
enabled = true
port = 54323

[functions.pipedrive-search]
verify_jwt = false

[functions.transcribe-call]
verify_jwt = false

[functions.pipedrive-add-note]
verify_jwt = false

[functions.cleanup-old-recordings]
verify_jwt = false

[functions.extension-config]
verify_jwt = false
